# Generated by Django 3.1.8 on 2021-05-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='blog_date',
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='blog_content',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='blog_title',
            field=models.CharField(max_length=20),
        ),
    ]
