# Generated by Django 3.1.8 on 2021-05-26 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_auto_20210526_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='blog_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='blog_content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='blog_title',
            field=models.CharField(max_length=80),
        ),
    ]
