# Generated by Django 3.1.8 on 2021-05-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0008_blogdata_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='u_id',
            field=models.IntegerField(),
        ),
    ]
