# Generated by Django 3.1.8 on 2021-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_auto_20210527_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='blog_content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='blog_title',
            field=models.CharField(max_length=100),
        ),
    ]
